name: Pull Request Checks

on:
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on:
      - self-hosted

    steps:
      - name: Checkout Repo
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Use Node.js
        uses: actions/setup-node@04c56d2f954f1e4c69436aa54cfef261a018f458
        with:
          cache: npm
          node-version-file: .nvmrc

      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: npm test
